<?php
include "scripts/inc_scripts.php";

//If user is not logged in, don’t allow them to use the page...
if (empty($_SESSION['loggedIn']) || $_SESSION['loggedIn'] == false){
	header("Location: " . ROOT_URL);
}
?>

<!DOCTYPE html>
<html>	
	<head>
		<!-- Include index stylesheet since it includes styles for 1/3 width columns -->
		<link rel="stylesheet" type="text/css" href="<?php echo ROOT_URL; ?>/res/style/css/index.php" />
		
		<link rel="stylesheet" type="text/css" href="<?php echo ROOT_URL; ?>/res/style/css/homework.php" />
		
		<script type="text/javascript">
			/*Get variables from PHP.*/
			var uid = <?php echo($_SESSION['userData']['ID']); ?>;
			var userType = "<?php echo($_SESSION['userData']['type']); ?>";
		</script>
		
		<!-- Changed included JS file to the relevant one for homework. -->
		<script type="text/javascript" src="<?php echo ROOT_URL; ?>/scripts/js/homework.js"></script>
		
		<title>Milkshake</title>
	</head>
	
	<!-- Changed all IDs from messags-* to hwk-* -->
	<body id="hwk-body">
		<!-- Removed the messages reply section. -->
		
		<section id="hwk-navbar">
			<?php include(ROOT_DIR . "/res/style/html/navbar.php"); ?>
		</section>
		
		<!-- These will be generated by JavaScript with custom 'data-*' attributes,
			to ID the messages. -->
		<section id="hwk-main-content">
			<div id="hwk-preview-pane">
				<ul id="hwk-preview-list">
				</ul>
			</div>
			
			<div id="hwk-content-pane">
				<h1 id="hwk-content-header">Nothing to Show Yet</h1>
				
				<!-- The following divs are designed
				in CSS to be displayed as 2 columns. -->
				<div>
					<h2 id="hwk-content-teacher"></h2>
				</div>
				
				<div>
					<select id="hwk-status">
						<option value="I">Incomplete</option>
						<option value="C">Complete</option>
						<option value="H">Handed In</option>
						<option value="O">Overdue</option>
					</select>
				</div>
				<hr />
				
				<div id="hwk-content">
					<p>Nothing to show yet.</p>
				</div>
			</div>
		</section>
		
		<!-- Removed reply button -->
	</body>
</html>